CREATE TABLE comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    menssage   VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    resolved     BOOLEAN,
    profile_id BIGINT,
    topic_id   BIGINT,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE course
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    category VARCHAR(255),
    CONSTRAINT pk_course PRIMARY KEY (id)
);

CREATE TABLE profile
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    id_user UUID                                    NOT NULL,
    CONSTRAINT pk_profile PRIMARY KEY (id)
);

CREATE TABLE topic
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255),
    menssage   VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    status     VARCHAR(255),
    profile_id BIGINT                                  NOT NULL,
    course_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_topic PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       UUID NOT NULL,
    name     VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_PROFILE FOREIGN KEY (profile_id) REFERENCES profile (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_TOPIC FOREIGN KEY (topic_id) REFERENCES topic (id);

ALTER TABLE profile
    ADD CONSTRAINT FK_PROFILE_ON_ID_USER FOREIGN KEY (id_user) REFERENCES users (id);

ALTER TABLE topic
    ADD CONSTRAINT FK_TOPIC_ON_COURSE FOREIGN KEY (course_id) REFERENCES course (id);

ALTER TABLE topic
    ADD CONSTRAINT FK_TOPIC_ON_PROFILE FOREIGN KEY (profile_id) REFERENCES profile (id);